name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Force Tailwind v4 PostCSS config
        run: |
          echo "module.exports = { plugins: { '@tailwindcss/postcss': {} } };" > postcss.config.js
          echo '@import "tailwindcss";' > src/styles.css

      - name: Build Angular project
        run: npm run build

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload to S3
        run: |
          aws s3 sync dist/portfolio-final/browser s3://rishma-portfolio-site --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id EXQIR3MGHO7CU --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
