name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Remove ALL old cache (Tailwind v3 → v4 fix)
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          rm -rf ~/.npm
          echo "Old cache removed."

      - name: Install Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies (fresh)
        run: npm install

      - name: Show PostCSS config (debug)
        run: cat postcss.config.js

      - name: Build Angular Project
        run: npm run build

      - name: Upload to S3
        run: |
          aws s3 sync dist/portfolio-final/browser s3://rishma-portfolio-site --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: CloudFront Cache Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id EXQIR3MGHO7CU \
            --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
