name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Remove all old caches — FORCE CLEAN BUILD
      - name: Remove old node_modules & npm cache
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          rm -rf ~/.npm

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies fresh
        run: npm install

      - name: Show PostCSS Config
        run: cat postcss.config.js

      - name: Build Angular App
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync files to S3
        run: aws s3 sync ./dist/portfolio-final/browser s3://rishma-portfolio-site --delete

      - name: CloudFront Cache Invalidation
        run: aws cloudfront create-invalidation --distribution-id EXQIR3MGHO7CU --paths "/*"
